---

services:
  - name: "bitlbee"
    enabled: "yes"

repositories:
  - name: 'bitlbee.org'
    repo: 'deb http://code.bitlbee.org/debian/master/xenial/amd64/ ./'
    key: 'https://code.bitlbee.org/debian/release.key'
  - name: 'jgeboski'
    repo: 'deb http://download.opensuse.org/repositories/home:/jgeboski/xUbuntu_16.04 ./'
    key: 'https://jgeboski.github.io/obs.key'
  - name: "sublime"
    repo: "deb https://download.sublimetext.com/ apt/stable/"
    key: "https://download.sublimetext.com/sublimehq-pub.gpg"
  - name: "handbrake"
    repo: "deb http://ppa.launchpad.net/stebbins/handbrake-releases/ubuntu xenial main"
    key: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x8771ADB0816950D8"
  - name: "multisystem"
    repo: "deb http://liveusb.info/multisystem/depot all main"
    key: "http://liveusb.info/multisystem/depot/multisystem.asc"
  - name: "virtualbox"
    repo: "deb https://download.virtualbox.org/virtualbox/debian xenial contrib"
    key: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
  - name: "spotify"
    repo: 'deb http://repository.spotify.com stable non-free'
    key:  'http://keyserver.ubuntu.com/pks/lookup?op=hget&search=190C3802FF54A2688709EFAA6D3CF129'


soft:
  - "bitlbee"
  - "bitlbee-facebook"
  - "chromium-browser"
  - "cifs-utils"
  - "feh"
  - "flashplugin-installer"
  - "gimp"
  - "gparted"
  - "i3"
  - "irssi"
  - "keepass2"
  - "libreoffice"
  - "lightdm"
  - "lightdm-gtk-greeter"
  - "mutt"
  - "nmap"
  - "pidgin-sipe"
  - "python-cheetah"
  - "python-virtualenv"
  - "ranger"
  - "rdesktop"
  - "resolvconf"
  - "sublime-text"
  - "xfce4"
  - "xfce4-terminal"
  - "xmms2"
  - "virtualbox"
  - "vlc"
  - "spotify-client"

soft_deb:
  - "https://downloads.slack-edge.com/linux_releases/slack-desktop-3.3.3-amd64.deb"
  - "https://releases.hashicorp.com/vagrant/2.2.0/vagrant_2.2.0_x86_64.deb"
  - "https://zoom.us/client/latest/zoom_amd64.deb"

locale:
  - nl_BE.UTF-8
  - en_US.UTF-8

configurationfiles:
# sublime
  - name: "sublime/Package Control.sublime-settings"
    path: "~/.config/sublime-text-3/Packages/User/"
  - name: "sublime/Preferences.sublime-settings"
    path: "~/.config/sublime-text-3/Packages/User/"
# mutt
  - name: "mutt/.muttrc"
    path: "~/"
# bin
  - name: "bin/chatspace.sh"
    mode: "0750"
    path: "~/bin/"
  - name: "bin/setscreens.sh"
    mode: "0750"
    path: "~/bin/"
# i3wm
  - name: "i3wm/config"
    path: "~/.i3/"
  - name: "i3wm/chatspace.json"
    path: "~/.i3/"
  # - name: "i3wm/background.sh"
  #   path: "~/.i3/"
  # - name: "i3wm/lockimg.sh"
  #   path: "~/.i3/"
  # - name: "i3wm/lock.png"
  #   path: "~/.i3/"
# self
  - name: ".bash_workspaces.sh"
    mode: "0755"
    path: "~/"

