---
- name: restart sshd
  service:
    name: ssh
    state: restarted
    enabled: yes
  become: yes

- name: restart ntpd
  service:
    name: ntp
    state: restarted
    enabled: yes
  become: yes

