---


soft:
  # - "libswitch-perl"
  - "acl"   ### needed for ansible become_user shenanigans ( http://docs.ansible.com/ansible/latest/become.html#becoming-an-unprivileged-user )
  - "apt-transport-https"
  - "atop"
  - "bash-completion"
  - "bzip2"
  - "curl"
  - "daemon"
  - "dos2unix"
  - "dstat"
  - "git"
  - "htop"
  - "iotop"
  - "irqbalance"
  - "links"
  - "lldpd"
  - "lsof"
  - "lsscsi"
  - "lynx"
  - "mlocate"
  - "net-tools"
  - "ntp"
  - "openssh-server"
  - "postfix"
  - "python-dev"
  - "python-gtk2"
  - "python-pip"
  - "rng-tools"
  - "rsync"
  - "screen"
  - "sudo"
  - "sysstat"
  - "sysv-rc-conf"
  - "telnet"
  - "tmux"
  - "tree"
  - "unzip"
  - "vim"
  - "virtualenv"
  - "xfsprogs"
  - "zip"


services:
  - name: "sshd"
    enabled: "yes"
  - name: "ntp"
    enabled: "yes"
  - name: "rng-tools"
    enabled: "yes"


locale:
  - nl_BE.UTF-8
  - en_US.UTF-8

