---

- name: set default shell for new users
  lineinfile:
    dest: "/etc/default/useradd"
    regexp: '^SHELL='
    line: 'SHELL=/bin/bash'
    state: present
  become: yes

- name: lets install the basic crap
  import_tasks: install.yml

- name: rng-tools config
  lineinfile:
    path: /etc/default/rng-tools
    regexp: "^HRNGDEVICE=.*"
    line: "HRNGDEVICE=/dev/random"
    state: present
  register: rng_config
  when: ansible_virtualization_role == "guest"
  become: yes

- name: reload rng-tools
  service:
    name: rng-tools
    state: restarted
  when: ansible_virtualization_role == "guest" and rng_config.changed
  become: yes

- name: lets set the default locale
  import_tasks: locale.yml

- name: set default shell for new users
  lineinfile:
    dest: "/etc/default/useradd"
    regexp: '^SHELL='
    line: 'SHELL=/bin/bash'
    state: present
  become: yes

- name: sshd config
  lineinfile:
  args:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{item.reg}}"
    line: "{{item.line}}"
    state: present
  notify: restart sshd
  become: yes
  with_items:
    - {reg: "PermitRootLogin",line: "PermitRootLogin no"}
    - {reg: "Port ",line: "Port 22"}

- name: prefer ipv4 over ipv6
  lineinfile:
    dest: "/etc/gai.conf"
    regexp: 'precedence ::ffff:0:0/96'
    line: 'precedence ::ffff:0:0/96  100'
    state: present
  become: yes
